### ISSUE TITLE
OSX 10.8 build error: "mconf.c ... ‘SIGWINCH’ undeclared"

### ISSUE THREAD

**Issue by mariobaldini** [mozilla-b2g/android-device-panda#1]
On OSX 10.8 ML / Xcode 4.4.1 

Build error: 
B2G/external/busybox/scripts/kconfig/mconf.c: error: ‘SIGWINCH’ undeclared (first use in this function)

http://pastebin.mozilla.org/1756536

Note: emulator profile builds and run successfully (prerequisites seems to be ok). Error only occurs on config.sh pandaboard.
Also tested with a fresh repo clone @ Aug 14

**Comment by mariobaldini** [comment]
Update:

In MaxOSX10.6.sdk/usr/include/sys/signal.h SIGWINCH is always declared. 

But in MacOSX10.[7-8].sdk it is conditional.

#if  (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
#define SIGWINCH 28 /\* window size changes _/
#define SIGINFO 29  /_ information request */
#endif

Although not sure why SIGWINCH isn't properly declared on SDK.10.7-8 case, I assume that the included busybox requires strictly sdk10.6. 

How could I force busybox be compiled using SDK 10.6's libs?

**Comment by mariobaldini** [comment]
It seems that the busybox version used indeed has some build issues on OSX, and the last version has already been updated to address that:

http://git.busybox.net/busybox/tree/scripts/kconfig/mconf.c
(line 12-13)

Reference:
http://www.digipedia.pl/usenet/thread/18071/27305/
http://git.busybox.net/busybox/commit/scripts/kconfig/mconf.c?id=9b78e14dfb891e3f53685e284bc9d5e3bf25f5a6

**Comment by armenzg** [comment]
I'm hitting the same issue.
Should I move doing B2G builds inside of Ubuntu in VirtualBox?

**Comment by nickpresta** [comment]
This issue still persist today with my config target set to `galaxy-nexus`. Will just attempt to build inside Debian 6 in VMware Fusion.

**Comment by kikyoungkwon** [comment]
This issue is still there for galaxy-nexus target. What is the solution for it?

B2G/external/busybox/scripts/kconfig/mconf.c:469: error: ‘SIGWINCH’ undeclared (first use in this function)

**Comment by ozten** [comment]
This is an issue when following the [APC build instructions](https://github.com/apc-io/apc-firefox-os/blob/master/building-guide.md) on a Mac.

**Comment by MartijnR** [comment]
experiencing same `CIGWINCH undeclared` issue when building for Galaxy Nexus on OS X 10.9 

`[...]/B2G/external/busybox/scripts/kconfig/mconf.c:469:12: error: use of undeclared identifier 'SIGWINCH'
    sigaction(SIGWINCH, &sa, NULL);`

**Comment by csurface** [comment]
Also seeing the issue building galaxy-nexus on OS X 10.9.1.  I extracted the 10.6 SDK just yesterday from an Xcode 4.3 for Lion package.  Comparing the signal.h file in 10.6 to 10.9, it appears that  SIGWINCH is declared the same way in both files (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)).  I'm wondering if this is a different flavor of 10.6 compared to what mariobaldini was seeing originally.

I will try to hack around it, but I'm wondering what else might go wrong due to missing defines.
